/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./popup/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Toàn bộ hệ thống màu của bạn
        "surface-bright": "#37393b",
        "on-primary-container": "#c8daff",
        "secondary-container": "#34a373",
        "inverse-primary": "#005db6",
        "on-secondary-container": "#00311e",
        "on-secondary": "#003823",
        "on-tertiary": "#003548",
        surface: "#121416",
        "on-secondary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        secondary: "#71dba6",
        "inverse-surface": "#e2e2e5",
        "surface-container-low": "#1a1c1e",
        "outline-variant": "#424752",
        "primary-container": "#005eb8",
        "on-primary-fixed": "#001b3d",
        "surface-container-lowest": "#0c0e10",
        "on-primary": "#003063",
        "on-background": "#e2e2e5",
        "on-error": "#690005",
        "primary-fixed": "#d6e3ff",
        "tertiary-fixed-dim": "#75d1ff",
        "primary-fixed-dim": "#a9c7ff",
        "tertiary-container": "#006789",
        tertiary: "#75d1ff",
        primary: "#a9c7ff",
        "on-tertiary-fixed": "#001e2b",
        "error-container": "#93000a",
        "tertiary-fixed": "#c2e8ff",
        "on-surface-variant": "#c2c6d4",
        "surface-tint": "#a9c7ff",
        error: "#ffb4ab",
        "on-tertiary-container": "#ade1ff",
        "on-secondary-fixed-variant": "#005235",
        outline: "#8c919d",
        "surface-container-highest": "#333537",
        "surface-dim": "#121416",
        "on-primary-fixed-variant": "#00468c",
        "secondary-fixed": "#8df7c1",
        background: "#121416",
        "surface-variant": "#333537",
        "surface-container": "#1e2022",
        "inverse-on-surface": "#2f3133",
        "surface-container-high": "#282a2c",
        "secondary-fixed-dim": "#71dba6",
        "on-surface": "#e2e2e5",
        "on-tertiary-fixed-variant": "#004d67",
        red: {
          500: "#ef4444",
        },
        amber: {
          500: "#f59e0b",
        },
        lime: {
          500: "#84cc16",
        },
        green: {
          500: "#22c55e",
        },
        emerald: {
          500: "#10b981",
        },
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
